### ISSUE TITLE
关于爬取官网照片的问题

### ISSUE THREAD

**Issue by PzoHua** [yhangf/PythonCrawler#6]
@yhangf 你好，我在测试你的项目https://github.com/yhangf/PythonCrawler/blob/master/spiderFile/student_img.py
时遇到了困难。在代码第20行，我爬取的照片地址在学号后面，还有十位随机字符（数字与字母组合），即
student_url=url+201110000001PsqfH7TK9w
而不只是student_url=url+201110000001
请问这个怎么解决？第一次提问，如表达不到位，请谅解。谢谢！

**Comment by yhangf** [comment]
那你这个估计爬不了哦，如果你能获取到十位随机字符。

**Comment by PzoHua** [comment]
好的，谢谢你！
